package org.telegram.ui;
import android.content.Context;import android.view.Gravity;import android.view.View;import android.widget.*;import org.telegram.messenger.*;import org.telegram.ui.ActionBar.*;import org.telegram.ui.Components.*;import java.util.ArrayList;
public class DevGramPluginReportsActivity extends BaseFragment{
 private final ArrayList<DevGramPlugins.PluginReport> reports=new ArrayList<>();private LinearLayout content;private int loadGeneration;
 @Override public View createView(Context c){actionBar.setBackButtonImage(R.drawable.ic_ab_back);actionBar.setTitle("Жалобы на плагины");actionBar.setActionBarMenuOnItemClick(new ActionBar.ActionBarMenuOnItemClick(){@Override public void onItemClick(int id){if(id==-1)finishFragment();}});content=new LinearLayout(c);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(12),AndroidUtilities.dp(16),AndroidUtilities.dp(28));content.setBackgroundColor(Theme.getColor(Theme.key_windowBackgroundGray,resourceProvider));ScrollView s=new ScrollView(c);s.addView(content);loadReports(0);return fragmentView=s;}
 @Override public void onResume(){super.onResume();if(content!=null)loadReports(0);}
 private void loadReports(int attempt){final int generation=++loadGeneration;DevGramPlugins.fetchPluginReports(x->{if(content==null||generation!=loadGeneration)return;reports.clear();reports.addAll(x);render(getContext());if(x.isEmpty()&&attempt<2)AndroidUtilities.runOnUIThread(()->{if(content!=null&&generation==loadGeneration)loadReports(attempt+1);},1200L);});}
 private void render(Context c){content.removeAllViews();content.addView(text(c,"ОТКРЫТЫЕ ЖАЛОБЫ · "+reports.size(),12,true,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,5,0,10));if(reports.isEmpty()){TextView e=text(c,"Жалоб на плагины нет",16,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider));e.setGravity(Gravity.CENTER);e.setPadding(0,AndroidUtilities.dp(52),0,0);content.addView(e);return;}for(DevGramPlugins.PluginReport r:reports)content.addView(card(c,r),LayoutHelper.createLinear(-1,-2,0,0,0,10));}
 private View card(Context c,DevGramPlugins.PluginReport r){LinearLayout v=new LinearLayout(c);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(14),AndroidUtilities.dp(16),AndroidUtilities.dp(14));v.setBackground(Theme.createSimpleSelectorRoundRectDrawable(AndroidUtilities.dp(19),Theme.getColor(Theme.key_windowBackgroundWhite,resourceProvider),Theme.getColor(Theme.key_listSelector,resourceProvider)));v.addView(text(c,r.pluginId,17,true,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText,resourceProvider)));TextView tag=text(c,"ЖАЛОБА НА ПЛАГИН",11,true,Theme.getColor(Theme.key_text_RedRegular,resourceProvider));tag.setPadding(AndroidUtilities.dp(7),AndroidUtilities.dp(3),AndroidUtilities.dp(7),AndroidUtilities.dp(3));tag.setBackground(Theme.createRoundRectDrawable(AndroidUtilities.dp(7),Theme.multAlpha(Theme.getColor(Theme.key_text_RedRegular,resourceProvider),.12f)));v.addView(tag,LayoutHelper.createLinear(-2,-2,0,7,0,8));v.addView(text(c,r.reason,15,false,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText,resourceProvider)));v.addView(text(c,"Отправитель: "+r.reporterId+(r.date>0?"  •  "+android.text.format.DateFormat.format("dd.MM.yyyy HH:mm",r.date):""),12,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,7,0,0));v.setOnClickListener(x->actions(c,r));return v;}
 private void actions(Context c,DevGramPlugins.PluginReport r){LinearLayout root=sheetRoot(c,"Жалоба на "+r.pluginId,r.reason);BottomSheet[] ref=new BottomSheet[1];addAction(c,root,"Отклонить жалобу","Нарушение не подтвердилось",false,()->resolve(r,0,ref[0]));addAction(c,root,"Скрыть из каталога","Плагин можно будет отправить повторно",true,()->resolve(r,1,ref[0]));addAction(c,root,"Скрыть и заблокировать","Запретить повторную публикацию этого файла",true,()->resolve(r,2,ref[0]));BottomSheet.Builder b=new BottomSheet.Builder(c);b.setApplyBottomPadding(false);b.setCustomView(root);ref[0]=b.create();ref[0].show();}
 private void resolve(DevGramPlugins.PluginReport r,int action,BottomSheet s){EditText input=themedInput(getContext(),"Коротко объясните решение");new AlertDialog.Builder(getContext()).setTitle(action==0?"Отклонить жалобу":action==1?"Скрыть плагин":"Скрыть и заблокировать").setMessage("Эта причина будет показана пользователю.").setView(input).setPositiveButton("Подтвердить",(d,w)->{String why=input.getText().toString().trim();if(why.isEmpty()){BulletinFactory.of(this).createErrorBulletin("Укажите причину").show();return;}if(DevGramPlugins.resolvePluginReport(r,action,why)){reports.remove(r);s.dismiss();render(getContext());BulletinFactory.of(this).createSimpleBulletin(R.raw.contact_check,action==0?"Жалоба отклонена":action==1?"Плагин скрыт":"Плагин скрыт и заблокирован").show();}}).setNegativeButton("Отмена",null).show();}
 static EditText themedInput(Context c,String hint){EditText i=new EditText(c);i.setHint(hint);i.setTextColor(Theme.getColor(Theme.key_dialogTextBlack));i.setHintTextColor(Theme.getColor(Theme.key_groupcreate_hintText));i.setBackground(Theme.createRoundRectDrawable(AndroidUtilities.dp(14),Theme.getColor(Theme.key_dialogBackground)));i.setPadding(AndroidUtilities.dp(14),AndroidUtilities.dp(12),AndroidUtilities.dp(14),AndroidUtilities.dp(12));i.setMinLines(2);return i;}
 static LinearLayout sheetRoot(Context c,String title,String sub){LinearLayout r=new LinearLayout(c);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(14),AndroidUtilities.dp(16),AndroidUtilities.dp(22));r.addView(text(c,title,21,true,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText)));r.addView(text(c,sub,14,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText)),LayoutHelper.createLinear(-1,-2,0,4,0,14));return r;}
 static void addAction(Context c,LinearLayout root,String title,String sub,boolean danger,Runnable run){LinearLayout row=new LinearLayout(c);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(AndroidUtilities.dp(15),AndroidUtilities.dp(12),AndroidUtilities.dp(15),AndroidUtilities.dp(12));row.setBackground(Theme.createSimpleSelectorRoundRectDrawable(AndroidUtilities.dp(14),Theme.getColor(Theme.key_windowBackgroundGray),Theme.getColor(Theme.key_listSelector)));row.addView(text(c,title,16,true,danger?Theme.getColor(Theme.key_text_RedRegular):Theme.getColor(Theme.key_windowBackgroundWhiteBlackText)));row.addView(text(c,sub,13,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText)),LayoutHelper.createLinear(-1,-2,0,3,0,0));row.setOnClickListener(v->run.run());root.addView(row,LayoutHelper.createLinear(-1,-2,0,0,0,8));}
 static TextView text(Context c,String s,int z,boolean b,int color){TextView t=new TextView(c);t.setText(s);t.setTextSize(z);t.setTextColor(color);if(b)t.setTypeface(AndroidUtilities.bold());return t;}
}
