package org.telegram.ui;
import android.content.Context;import android.view.Gravity;import android.view.View;import android.widget.*;import org.telegram.messenger.*;import org.telegram.ui.ActionBar.*;import org.telegram.ui.Components.*;import java.util.ArrayList;
public class DevGramReviewReportsActivity extends BaseFragment{
 private final ArrayList<DevGramPlugins.ReviewReport> reports=new ArrayList<>();private LinearLayout content;private int loadGeneration;
 @Override public View createView(Context c){actionBar.setBackButtonImage(R.drawable.ic_ab_back);actionBar.setTitle("Жалобы на отзывы");actionBar.setActionBarMenuOnItemClick(new ActionBar.ActionBarMenuOnItemClick(){@Override public void onItemClick(int id){if(id==-1)finishFragment();}});content=new LinearLayout(c);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(12),AndroidUtilities.dp(16),AndroidUtilities.dp(28));content.setBackgroundColor(Theme.getColor(Theme.key_windowBackgroundGray,resourceProvider));ScrollView s=new ScrollView(c);s.addView(content);loadReports(0);return fragmentView=s;}
 @Override public void onResume(){super.onResume();if(content!=null)loadReports(0);}
 private void loadReports(int attempt){final int generation=++loadGeneration;DevGramPlugins.fetchReviewReports(x->{if(content==null||generation!=loadGeneration)return;reports.clear();reports.addAll(x);render(getContext());if(x.isEmpty()&&attempt<2)AndroidUtilities.runOnUIThread(()->{if(content!=null&&generation==loadGeneration)loadReports(attempt+1);},1200L);});}
 private void render(Context c){content.removeAllViews();content.addView(DevGramPluginReportsActivity.text(c,"ОТКРЫТЫЕ ЖАЛОБЫ · "+reports.size(),12,true,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,5,0,10));if(reports.isEmpty()){TextView e=DevGramPluginReportsActivity.text(c,"Жалоб на отзывы нет",16,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider));e.setGravity(Gravity.CENTER);e.setPadding(0,AndroidUtilities.dp(52),0,0);content.addView(e);return;}for(DevGramPlugins.ReviewReport r:reports)content.addView(card(c,r),LayoutHelper.createLinear(-1,-2,0,0,0,10));}
 private View card(Context c,DevGramPlugins.ReviewReport r){LinearLayout v=new LinearLayout(c);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(14),AndroidUtilities.dp(16),AndroidUtilities.dp(14));v.setBackground(Theme.createSimpleSelectorRoundRectDrawable(AndroidUtilities.dp(19),Theme.getColor(Theme.key_windowBackgroundWhite,resourceProvider),Theme.getColor(Theme.key_listSelector,resourceProvider)));v.addView(DevGramPluginReportsActivity.text(c,r.pluginId,17,true,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText,resourceProvider)));v.addView(DevGramPluginReportsActivity.text(c,r.reason,15,false,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,8,0,0));v.addView(DevGramPluginReportsActivity.text(c,"Отзыв пользователя: "+r.reviewUserId+"  •  пожаловался: "+r.reporterId,12,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,7,0,0));v.setOnClickListener(x->actions(c,r));return v;}
 private void actions(Context c,DevGramPlugins.ReviewReport r){LinearLayout root=DevGramPluginReportsActivity.sheetRoot(c,"Жалоба на отзыв",r.reason);BottomSheet[] ref=new BottomSheet[1];DevGramPluginReportsActivity.addAction(c,root,"Открыть отзывы","Быстро проверить отзыв пользователя "+r.reviewUserId,false,()->{ref[0].dismiss();openReviews(r.pluginId);});DevGramPluginReportsActivity.addAction(c,root,"Закрыть без удаления","Оставить отзыв в каталоге",false,()->resolve(r,false,ref[0]));DevGramPluginReportsActivity.addAction(c,root,"Удалить отзыв","Удалить нарушающий отзыв",true,()->resolve(r,true,ref[0]));BottomSheet.Builder b=new BottomSheet.Builder(c);b.setApplyBottomPadding(false);b.setCustomView(root);ref[0]=b.create();ref[0].show();}
 private void openReviews(String id){DevGramPlugins.fetchCatalogEntry(id,items->{if(items.isEmpty()){BulletinFactory.of(this).createErrorBulletin("Плагин не найден").show();return;}presentFragment(new DevGramPluginReviewsActivity(items.get(0)));});}
 private void resolve(DevGramPlugins.ReviewReport r,boolean del,BottomSheet s){EditText input=DevGramPluginReportsActivity.themedInput(getContext(),"Коротко объясните решение");new AlertDialog.Builder(getContext()).setTitle(del?"Удалить отзыв":"Отклонить жалобу").setMessage("Эта причина будет показана пользователю.").setView(input).setPositiveButton("Подтвердить",(d,w)->{String why=input.getText().toString().trim();if(why.isEmpty()){BulletinFactory.of(this).createErrorBulletin("Укажите причину").show();return;}if(DevGramPlugins.resolveReviewReport(r,del,why)){reports.remove(r);s.dismiss();render(getContext());BulletinFactory.of(this).createSimpleBulletin(R.raw.contact_check,del?"Отзыв удалён":"Жалоба закрыта").show();}}).setNegativeButton("Отмена",null).show();}
}
