package org.telegram.ui;
import android.content.Context;import android.view.Gravity;import android.view.View;import android.widget.*;import org.telegram.messenger.*;import org.telegram.ui.ActionBar.*;import org.telegram.ui.Components.*;import java.util.ArrayList;
public class DevGramPluginReportsActivity extends BaseFragment{
 private final ArrayList<DevGramPlugins.PluginReport> reports=new ArrayList<>();private LinearLayout content;
 @Override public View createView(Context c){actionBar.setBackButtonImage(R.drawable.ic_ab_back);actionBar.setTitle("Жалобы на плагины");actionBar.setActionBarMenuOnItemClick(new ActionBar.ActionBarMenuOnItemClick(){@Override public void onItemClick(int id){if(id==-1)finishFragment();}});content=new LinearLayout(c);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(12),AndroidUtilities.dp(16),AndroidUtilities.dp(28));content.setBackgroundColor(Theme.getColor(Theme.key_windowBackgroundGray,resourceProvider));ScrollView s=new ScrollView(c);s.addView(content);DevGramPlugins.fetchPluginReports(x->{reports.clear();reports.addAll(x);render(c);});return fragmentView=s;}
 private void render(Context c){content.removeAllViews();content.addView(text(c,"ОТКРЫТЫЕ ЖАЛОБЫ · "+reports.size(),12,true,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,5,0,10));if(reports.isEmpty()){TextView e=text(c,"Жалоб на плагины нет",16,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider));e.setGravity(Gravity.CENTER);e.setPadding(0,AndroidUtilities.dp(52),0,0);content.addView(e);return;}for(DevGramPlugins.PluginReport r:reports)content.addView(card(c,r),LayoutHelper.createLinear(-1,-2,0,0,0,10));}
 private View card(Context c,DevGramPlugins.PluginReport r){LinearLayout v=new LinearLayout(c);v.setOrientation(LinearLayout.VERTICAL);v.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(14),AndroidUtilities.dp(16),AndroidUtilities.dp(14));v.setBackground(Theme.createSimpleSelectorRoundRectDrawable(AndroidUtilities.dp(19),Theme.getColor(Theme.key_windowBackgroundWhite,resourceProvider),Theme.getColor(Theme.key_listSelector,resourceProvider)));v.addView(text(c,r.pluginId,17,true,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText,resourceProvider)));TextView tag=text(c,"ЖАЛОБА НА ПЛАГИН",11,true,Theme.getColor(Theme.key_text_RedRegular,resourceProvider));tag.setPadding(AndroidUtilities.dp(7),AndroidUtilities.dp(3),AndroidUtilities.dp(7),AndroidUtilities.dp(3));tag.setBackground(Theme.createRoundRectDrawable(AndroidUtilities.dp(7),Theme.multAlpha(Theme.getColor(Theme.key_text_RedRegular,resourceProvider),.12f)));v.addView(tag,LayoutHelper.createLinear(-2,-2,0,7,0,8));v.addView(text(c,r.reason,15,false,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText,resourceProvider)));v.addView(text(c,"Отправитель: "+r.reporterId+(r.date>0?"  •  "+android.text.format.DateFormat.format("dd.MM.yyyy HH:mm",r.date):""),12,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText,resourceProvider)),LayoutHelper.createLinear(-1,-2,0,7,0,0));v.setOnClickListener(x->actions(c,r));return v;}
 private void actions(Context c,DevGramPlugins.PluginReport r){LinearLayout root=sheetRoot(c,"Жалоба на "+r.pluginId,r.reason);BottomSheet[] ref=new BottomSheet[1];addAction(c,root,"Закрыть жалобу","Нарушение не подтвердилось",false,()->resolve(r,false,ref[0]));addAction(c,root,"Скрыть плагин","Убрать его из каталога",true,()->resolve(r,true,ref[0]));BottomSheet.Builder b=new BottomSheet.Builder(c);b.setApplyBottomPadding(false);b.setCustomView(root);ref[0]=b.create();ref[0].show();}
 private void resolve(DevGramPlugins.PluginReport r,boolean hide,BottomSheet s){if(DevGramPlugins.resolvePluginReport(r,hide)){reports.remove(r);s.dismiss();render(getContext());BulletinFactory.of(this).createSimpleBulletin(R.raw.contact_check,hide?"Плагин скрыт":"Жалоба закрыта").show();}}
 static LinearLayout sheetRoot(Context c,String title,String sub){LinearLayout r=new LinearLayout(c);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(AndroidUtilities.dp(16),AndroidUtilities.dp(14),AndroidUtilities.dp(16),AndroidUtilities.dp(22));r.addView(text(c,title,21,true,Theme.getColor(Theme.key_windowBackgroundWhiteBlackText)));r.addView(text(c,sub,14,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText)),LayoutHelper.createLinear(-1,-2,0,4,0,14));return r;}
 static void addAction(Context c,LinearLayout root,String title,String sub,boolean danger,Runnable run){LinearLayout row=new LinearLayout(c);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(AndroidUtilities.dp(15),AndroidUtilities.dp(12),AndroidUtilities.dp(15),AndroidUtilities.dp(12));row.setBackground(Theme.createSimpleSelectorRoundRectDrawable(AndroidUtilities.dp(14),Theme.getColor(Theme.key_windowBackgroundGray),Theme.getColor(Theme.key_listSelector)));row.addView(text(c,title,16,true,danger?Theme.getColor(Theme.key_text_RedRegular):Theme.getColor(Theme.key_windowBackgroundWhiteBlackText)));row.addView(text(c,sub,13,false,Theme.getColor(Theme.key_windowBackgroundWhiteGrayText)),LayoutHelper.createLinear(-1,-2,0,3,0,0));row.setOnClickListener(v->run.run());root.addView(row,LayoutHelper.createLinear(-1,-2,0,0,0,8));}
 static TextView text(Context c,String s,int z,boolean b,int color){TextView t=new TextView(c);t.setText(s);t.setTextSize(z);t.setTextColor(color);if(b)t.setTypeface(AndroidUtilities.bold());return t;}
}
