package org.telegram.ui;
import android.content.Context;import android.view.Gravity;import android.view.View;import android.widget.FrameLayout;import android.widget.TextView;
import org.telegram.messenger.AndroidUtilities;import org.telegram.messenger.DevGramPlugins;import org.telegram.messenger.R;import org.telegram.ui.ActionBar.ActionBar;import org.telegram.ui.ActionBar.BaseFragment;import org.telegram.ui.ActionBar.Theme;import org.telegram.ui.Components.LayoutHelper;import org.telegram.ui.Components.UItem;import org.telegram.ui.Components.UniversalAdapter;import org.telegram.ui.Components.UniversalRecyclerView;import java.util.ArrayList;
public class DevGramPluginReviewsActivity extends BaseFragment{
 private final DevGramPlugins.CatalogEntry entry; private final ArrayList<DevGramPlugins.Review> reviews=new ArrayList<>(); private UniversalRecyclerView list;
 public DevGramPluginReviewsActivity(DevGramPlugins.CatalogEntry e){entry=e;}
 @Override public View createView(Context c){actionBar.setBackButtonImage(R.drawable.ic_ab_back);actionBar.setTitle("Отзывы · "+entry.name);actionBar.setActionBarMenuOnItemClick(new ActionBar.ActionBarMenuOnItemClick(){@Override public void onItemClick(int id){if(id==-1)finishFragment();}});FrameLayout root=new FrameLayout(c);list=new UniversalRecyclerView(this,this::fill,null,null);list.setBackgroundColor(Theme.getColor(Theme.key_windowBackgroundGray,resourceProvider));root.addView(list,LayoutHelper.createFrame(-1,-1,Gravity.FILL));DevGramPlugins.fetchReviews(entry.id,x->{reviews.clear();reviews.addAll(x);list.adapter.update(true);});return fragmentView=root;}
 private void fill(ArrayList<UItem> items,UniversalAdapter a){items.add(UItem.asHeader("Все отзывы ("+reviews.size()+")"));if(reviews.isEmpty()){items.add(UItem.asShadow("Отзывов пока нет."));return;}for(DevGramPlugins.Review r:reviews)items.add(UItem.asButton(r.hashCode(),R.drawable.msg_info,"★".repeat(Math.max(0,Math.min(5,r.rating)))+"  "+r.name,r.text));items.add(UItem.asShadow(null));}
}
