package org.telegram.ui;
import android.content.Context; import android.view.Gravity; import android.view.View; import android.widget.FrameLayout;
import org.telegram.messenger.DevGramPlugins; import org.telegram.messenger.R; import org.telegram.ui.ActionBar.ActionBar; import org.telegram.ui.ActionBar.AlertDialog; import org.telegram.ui.ActionBar.BaseFragment; import org.telegram.ui.ActionBar.Theme; import org.telegram.ui.Components.BulletinFactory; import org.telegram.ui.Components.LayoutHelper; import org.telegram.ui.Components.UItem; import org.telegram.ui.Components.UniversalAdapter; import org.telegram.ui.Components.UniversalRecyclerView; import java.util.ArrayList;
public class DevGramReviewReportsActivity extends BaseFragment {
 private final ArrayList<DevGramPlugins.ReviewReport> reports=new ArrayList<>(); private UniversalRecyclerView list;
 @Override public View createView(Context c){actionBar.setBackButtonImage(R.drawable.ic_ab_back);actionBar.setTitle("Жалобы на отзывы");actionBar.setActionBarMenuOnItemClick(new ActionBar.ActionBarMenuOnItemClick(){@Override public void onItemClick(int id){if(id==-1)finishFragment();}});FrameLayout root=new FrameLayout(c);list=new UniversalRecyclerView(this,this::fill,this::click,null);list.setBackgroundColor(Theme.getColor(Theme.key_windowBackgroundGray,resourceProvider));root.addView(list,LayoutHelper.createFrame(-1,-1,Gravity.FILL));DevGramPlugins.fetchReviewReports(x->{reports.clear();reports.addAll(x);list.adapter.update(true);});return fragmentView=root;}
 private void fill(ArrayList<UItem> items, UniversalAdapter a){items.add(UItem.asHeader("Открытые жалобы"));if(reports.isEmpty()){items.add(UItem.asShadow("Жалоб нет."));return;}for(int i=0;i<reports.size();i++){DevGramPlugins.ReviewReport r=reports.get(i);items.add(UItem.asButton(i,R.drawable.msg_report,"Плагин: "+r.pluginId,"Причина: "+r.reason+" · отзыв пользователя "+r.reviewUserId));}items.add(UItem.asShadow(null));}
 private void click(UItem item,View v,int p,float x,float y){if(item.id<0||item.id>=reports.size())return;DevGramPlugins.ReviewReport r=reports.get(item.id);new AlertDialog.Builder(getParentActivity()).setTitle("Обработать жалобу").setItems(new CharSequence[]{"Закрыть без удаления","Удалить отзыв"},(d,w)->{if(DevGramPlugins.resolveReviewReport(r,w==1)){reports.remove(r);list.adapter.update(true);BulletinFactory.of(this).createSimpleBulletin(R.raw.contact_check,"Жалоба обработана").show();}}).setNegativeButton("Отмена",null).show();}
}
